FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y iputils-ping
RUN apt install -y python3 python3-pip echo '8'
RUN apt-get install -y ansible
RUN mkdir -p /etc/ansible
RUN apt-get update
RUN apt-get upgrade -y
