FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install gcc python-dev libkrb5-dev -y
RUN apt-get install python3-pip -y 
RUN apt install krb5-user -y
RUN pip3 install pywinrm 
RUN pip3 install ansible
